# Generated by Django 5.1.6 on 2025-02-25 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('change_number', models.CharField(max_length=50)),
                ('requested_by', models.CharField(max_length=255)),
                ('date_of_request', models.DateField()),
                ('presented_to', models.CharField(max_length=255)),
                ('change_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reason', models.TextField()),
                ('effect_on_deliverables', models.TextField()),
                ('effect_on_organization', models.TextField()),
                ('effect_on_schedule', models.TextField()),
                ('effect_of_not_approving', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=255)),
                ('hours_reduction', models.IntegerField(default=0)),
                ('hours_increase', models.IntegerField(default=0)),
                ('dollars_reduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dollars_increase', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('change_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_items', to='change_requests.changerequest')),
            ],
        ),
    ]
